version: '3.7'
volumes:
  aide_db_data:
    name: aide_db_data
#    external: true
  aide_files:
    name: aide_files
services:
  aide_app:
    hostname: 'aide_app_host' 
    build:
      context:  '.'
      dockerfile: 'Dockerfile'
    image: 'aide_app'
    volumes:
      - aide_db_data:/var/lib/postgresql/10/main
      - aide_files:/home/aide/files
      - .:/home/aide/app:cached
      - /srv/daera_sheep/predictions/crops/valid_ort16_odapi:/home/aide/images 
    ports:
      - '8080:8080'

# Overrides default command so things don't shut down after the process ends.
    #command: gunicorn --workers=4 --bind 0.0.0.0:9000 --log-level=debug --error-logfile=- --access-logfile=- --timeout 60 --preload app:APP
    #command: flask run --host 0.0.0.0 --port 9000